### ISSUE TITLE
前期推送 相关

### ISSUE THREAD

**Issue by bdzzh** [Lovely-Qianyun/Temporary-Things#1]
前期推送里的回信是长篇还是短篇几句话，问题之间有没有关联（比如一个人的问题有多条

**Comment by Lovely-Qianyun** [comment]
前期推送基本上属于长篇。  
同学们的问题可能不长，但是心理老师的回信会非常长，会简单介绍问题和问题的解决方案以及劝慰等等，类似于以前杂志上的“编者复读者信”。  
关于问题，它们之间基本不存在关联。有的同学询问的可能是**找不到npy，我很焦虑**，有的同学可能会问**周围同学很卷，我很焦虑**，所以这些推送还是比较好做模板的。  
如果一定要找到一些关联的话，那么问题可以大致分为生活方面和学习方面两种。
